//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSNote.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImageNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImageNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPSNote.Resources.ImageNames", typeof(ImageNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ic_clear.
        /// </summary>
        internal static string ic_clear {
            get {
                return ResourceManager.GetString("ic_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ic_eye.
        /// </summary>
        internal static string ic_eye {
            get {
                return ResourceManager.GetString("ic_eye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ic_eye_off.
        /// </summary>
        internal static string ic_eye_off {
            get {
                return ResourceManager.GetString("ic_eye_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ic_like_blue.
        /// </summary>
        internal static string ic_like_blue {
            get {
                return ResourceManager.GetString("ic_like_blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ic_like_gray.
        /// </summary>
        internal static string ic_like_gray {
            get {
                return ResourceManager.GetString("ic_like_gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ic_placeholder.
        /// </summary>
        internal static string ic_placeholder {
            get {
                return ResourceManager.GetString("ic_placeholder", resourceCulture);
            }
        }
    }
}
