//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSNote.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPSNote.Resources.UserMsg", typeof(UserMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have bad Longitude, Latitude.
        /// </summary>
        internal static string BadLongLat {
            get {
                return ResourceManager.GetString("BadLongLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Error.
        /// </summary>
        internal static string DataError {
            get {
                return ResourceManager.GetString("DataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email exists.
        /// </summary>
        internal static string EmailExist {
            get {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error edit pin!.
        /// </summary>
        internal static string ErrorEditPin {
            get {
                return ResourceManager.GetString("ErrorEditPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error going to area.
        /// </summary>
        internal static string ErrorGoingToArea {
            get {
                return ResourceManager.GetString("ErrorGoingToArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a linl. Do you want show is?.
        /// </summary>
        internal static string HaveALink {
            get {
                return ResourceManager.GetString("HaveALink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect.
        /// </summary>
        internal static string IncorrectPas {
            get {
                return ResourceManager.GetString("IncorrectPas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Mismatch.
        /// </summary>
        internal static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, add marker on the map.
        /// </summary>
        internal static string PlsAddPin {
            get {
                return ResourceManager.GetString("PlsAddPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, check your GPS settings.
        /// </summary>
        internal static string PlsCheckGPS {
            get {
                return ResourceManager.GetString("PlsCheckGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter &apos;Description&apos; of marker.
        /// </summary>
        internal static string PlsEnterDescroption {
            get {
                return ResourceManager.GetString("PlsEnterDescroption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter &apos;Name&apos; of marker.
        /// </summary>
        internal static string PlsEnterName {
            get {
                return ResourceManager.GetString("PlsEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select marker!.
        /// </summary>
        internal static string PlsSelectPin {
            get {
                return ResourceManager.GetString("PlsSelectPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share pin.
        /// </summary>
        internal static string SharePin {
            get {
                return ResourceManager.GetString("SharePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Email.
        /// </summary>
        internal static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error internet connection(((.
        /// </summary>
        internal static string WrongInternetConnect {
            get {
                return ResourceManager.GetString("WrongInternetConnect", resourceCulture);
            }
        }
    }
}
